// source: sense_api_toolbox.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sense.ToolboxQuery', null, global);
goog.exportSymbol('proto.sense.ToolboxQuery.Interface', null, global);
goog.exportSymbol('proto.sense.ToolboxQuery.Tools', null, global);
goog.exportSymbol('proto.sense.ToolboxResult', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sense.ToolboxQuery = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sense.ToolboxQuery.repeatedFields_, null);
};
goog.inherits(proto.sense.ToolboxQuery, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sense.ToolboxQuery.displayName = 'proto.sense.ToolboxQuery';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sense.ToolboxResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sense.ToolboxResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sense.ToolboxResult.displayName = 'proto.sense.ToolboxResult';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sense.ToolboxQuery.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sense.ToolboxQuery.prototype.toObject = function(opt_includeInstance) {
  return proto.sense.ToolboxQuery.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sense.ToolboxQuery} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sense.ToolboxQuery.toObject = function(includeInstance, msg) {
  var f, obj = {
    commandTool: jspb.Message.getFieldWithDefault(msg, 1, 0),
    iface: jspb.Message.getFieldWithDefault(msg, 2, 0),
    useIpv6: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    hostsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sense.ToolboxQuery}
 */
proto.sense.ToolboxQuery.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sense.ToolboxQuery;
  return proto.sense.ToolboxQuery.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sense.ToolboxQuery} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sense.ToolboxQuery}
 */
proto.sense.ToolboxQuery.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sense.ToolboxQuery.Tools} */ (reader.readEnum());
      msg.setCommandTool(value);
      break;
    case 2:
      var value = /** @type {!proto.sense.ToolboxQuery.Interface} */ (reader.readEnum());
      msg.setIface(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUseIpv6(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addHosts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sense.ToolboxQuery.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sense.ToolboxQuery.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sense.ToolboxQuery} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sense.ToolboxQuery.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommandTool();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getIface();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getUseIpv6();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getHostsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sense.ToolboxQuery.Tools = {
  NONE: 0,
  PING: 1,
  NETSTAT: 2,
  IPERF: 3,
  TRACEROUTE: 4
};

/**
 * @enum {number}
 */
proto.sense.ToolboxQuery.Interface = {
  UNKNOWN: 0,
  ETHERNET: 1,
  LTE4G: 2
};

/**
 * optional Tools command_tool = 1;
 * @return {!proto.sense.ToolboxQuery.Tools}
 */
proto.sense.ToolboxQuery.prototype.getCommandTool = function() {
  return /** @type {!proto.sense.ToolboxQuery.Tools} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sense.ToolboxQuery.Tools} value
 * @return {!proto.sense.ToolboxQuery} returns this
 */
proto.sense.ToolboxQuery.prototype.setCommandTool = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Interface iFace = 2;
 * @return {!proto.sense.ToolboxQuery.Interface}
 */
proto.sense.ToolboxQuery.prototype.getIface = function() {
  return /** @type {!proto.sense.ToolboxQuery.Interface} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sense.ToolboxQuery.Interface} value
 * @return {!proto.sense.ToolboxQuery} returns this
 */
proto.sense.ToolboxQuery.prototype.setIface = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional bool use_ipv6 = 3;
 * @return {boolean}
 */
proto.sense.ToolboxQuery.prototype.getUseIpv6 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sense.ToolboxQuery} returns this
 */
proto.sense.ToolboxQuery.prototype.setUseIpv6 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * repeated string hosts = 4;
 * @return {!Array<string>}
 */
proto.sense.ToolboxQuery.prototype.getHostsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.sense.ToolboxQuery} returns this
 */
proto.sense.ToolboxQuery.prototype.setHostsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.sense.ToolboxQuery} returns this
 */
proto.sense.ToolboxQuery.prototype.addHosts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sense.ToolboxQuery} returns this
 */
proto.sense.ToolboxQuery.prototype.clearHostsList = function() {
  return this.setHostsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sense.ToolboxResult.prototype.toObject = function(opt_includeInstance) {
  return proto.sense.ToolboxResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sense.ToolboxResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sense.ToolboxResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    commandResult: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sense.ToolboxResult}
 */
proto.sense.ToolboxResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sense.ToolboxResult;
  return proto.sense.ToolboxResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sense.ToolboxResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sense.ToolboxResult}
 */
proto.sense.ToolboxResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommandResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sense.ToolboxResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sense.ToolboxResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sense.ToolboxResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sense.ToolboxResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommandResult();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string command_result = 1;
 * @return {string}
 */
proto.sense.ToolboxResult.prototype.getCommandResult = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sense.ToolboxResult} returns this
 */
proto.sense.ToolboxResult.prototype.setCommandResult = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.sense);
